FROM dhi.io/python:3.13-dev AS builder
WORKDIR /app
RUN pip install --no-cache-dir uv
COPY uv.lock pyproject.toml ./
RUN uv sync --frozen --no-dev

FROM dhi.io/python:3.13
LABEL org.opencontainers.image.base.name="dhi.io/python:3.13"
WORKDIR /app
COPY --from=builder --chown=nonroot:nonroot /app/.venv /app/.venv
COPY --chown=nonroot:nonroot ./app ./app
USER nonroot

ENV PATH="/app/.venv/bin:$PATH"
ENV LOG_LEVEL=INFO \
    ROOT_PATH=/docker_demo \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1
EXPOSE 8000

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]