graph LR
    DOCUMENT["[Document]
Name: hardad
Version: SPDX-2.3
Created: 2026-04-20 09:05:30
Creators: Organization: Docker, Inc, Tool: docker-scout-1...
Namespace: https://docker.com/docker-scout/image/hardad-47...
Data License: CC0-1.0"]
    style DOCUMENT fill:#e1f5ff,stroke:#01579b,stroke-width:3px
    DocumentRoot["[Package - PackagePurpose.CONTAINER]
Name: hardad
Version: baseline
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
"]
    style DocumentRoot fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_93bd1c920854d3ea54091f1460ba6798["[Package]
Name: acl
Version: 2.3.2-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Guillem Jover <guillem@debian.org>
Originator: Person: Guillem Jover <guillem@debian.org>
"]
    style Package_93bd1c920854d3ea54091f1460ba6798 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_fb24b66b7b1d9c53fe8f144a3c3c40e5["[Package]
Name: adduser
Version: 3.152
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian Adduser Developers <adduser@packages.debian.org>
Originator: Person: Debian Adduser Developers <adduser@packages.debian.org>
"]
    style Package_fb24b66b7b1d9c53fe8f144a3c3c40e5 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_02cbae335032e5670250f30772387493["[Package]
Name: apt
Version: 3.0.3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: APT Development Team <deity@lists.debian.org>
Originator: Person: APT Development Team <deity@lists.debian.org>
"]
    style Package_02cbae335032e5670250f30772387493 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_4071db2ba67968632ef80ba78a0aa74a["[Package]
Name: attr
Version: 1:2.5.2-3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Guillem Jover <guillem@debian.org>
Originator: Person: Guillem Jover <guillem@debian.org>
"]
    style Package_4071db2ba67968632ef80ba78a0aa74a fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_1e8611cf6af09e2ddce30f997c8983bd["[Package]
Name: audit
Version: 1:4.0.2-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Laurent Bigonville <bigon@debian.org>
Originator: Person: Laurent Bigonville <bigon@debian.org>
"]
    style Package_1e8611cf6af09e2ddce30f997c8983bd fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_f7f688f0ad52acae46bf3241a4425fb8["[Package]
Name: base-files
Version: 13.8+deb13u4
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Santiago Vila <sanvila@debian.org>
Originator: Person: Santiago Vila <sanvila@debian.org>
"]
    style Package_f7f688f0ad52acae46bf3241a4425fb8 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_2c3f88677ad431593367af04c038ea5b["[Package]
Name: base-passwd
Version: 3.6.7
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Shadow package maintainers <pkg-shadow-devel@lists.alioth.debian.org>
Originator: Person: Shadow package maintainers <pkg-shadow-devel@lists.alioth.debian.org>
"]
    style Package_2c3f88677ad431593367af04c038ea5b fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_548d4a79f05a5a0daa8554f7ec815b8e["[Package]
Name: bash
Version: 5.2.37-2+b8
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Matthias Klose <doko@debian.org>
Originator: Person: Matthias Klose <doko@debian.org>
"]
    style Package_548d4a79f05a5a0daa8554f7ec815b8e fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_e9d2db56123850a45082110662f48ee3["[Package]
Name: bsdutils
Version: 1:2.41-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Chris Hofstaedtler <zeha@debian.org>
Originator: Person: Chris Hofstaedtler <zeha@debian.org>
"]
    style Package_e9d2db56123850a45082110662f48ee3 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_c9fbb1e6159fd2f3708cd103cda4f593["[Package]
Name: bzip2
Version: 1.0.8-6
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Anibal Monsalve Salazar <anibal@debian.org>
Originator: Person: Anibal Monsalve Salazar <anibal@debian.org>
"]
    style Package_c9fbb1e6159fd2f3708cd103cda4f593 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_e74252795d7e73ea88f0c17bec3531e3["[Package]
Name: ca-certificates
Version: 20250419
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Julien Cristau <jcristau@debian.org>
Originator: Person: Julien Cristau <jcristau@debian.org>
"]
    style Package_e74252795d7e73ea88f0c17bec3531e3 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_81ff56ccef416310950723196baeabb9["[Package]
Name: cdebconf
Version: 0.280
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian Install System Team <debian-boot@lists.debian.org>
Originator: Person: Debian Install System Team <debian-boot@lists.debian.org>
"]
    style Package_81ff56ccef416310950723196baeabb9 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_e06ca5ca1b19314aa5268c5a7e297742["[Package]
Name: coreutils
Version: 9.7-3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Michael Stone <mstone@debian.org>
Originator: Person: Michael Stone <mstone@debian.org>
"]
    style Package_e06ca5ca1b19314aa5268c5a7e297742 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_1e28e26d24b628f89a06f1dfdb406edb["[Package]
Name: dash
Version: 0.5.12-12
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Andrej Shadura <andrewsh@debian.org>
Originator: Person: Andrej Shadura <andrewsh@debian.org>
"]
    style Package_1e28e26d24b628f89a06f1dfdb406edb fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_2bb6caac75a6f4cabfc0d78016a8ebe1["[Package]
Name: db5.3
Version: 5.3.28+dfsg2-9
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian QA Group <packages@qa.debian.org>
Originator: Person: Debian QA Group <packages@qa.debian.org>
"]
    style Package_2bb6caac75a6f4cabfc0d78016a8ebe1 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_5e0124d66015307aa6f05eb1be5f5ea9["[Package]
Name: debconf
Version: 1.5.91
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debconf Developers <debconf-devel@lists.alioth.debian.org>
Originator: Person: Debconf Developers <debconf-devel@lists.alioth.debian.org>
"]
    style Package_5e0124d66015307aa6f05eb1be5f5ea9 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_3cd69302188ba1aa89f1e2aef1a9bc2f["[Package]
Name: debian-archive-keyring
Version: 2025.1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian Release Team <packages@release.debian.org>
Originator: Person: Debian Release Team <packages@release.debian.org>
"]
    style Package_3cd69302188ba1aa89f1e2aef1a9bc2f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_8535194951c4cf118f18adb326161c72["[Package]
Name: debianutils
Version: 5.23.2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Ileana Dumitrescu <ileanadumitrescu95@gmail.com>
Originator: Person: Ileana Dumitrescu <ileanadumitrescu95@gmail.com>
"]
    style Package_8535194951c4cf118f18adb326161c72 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_cde4da818c0e9c49e351a818c63522c0["[Package]
Name: diffutils
Version: 1:3.10-4
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Santiago Vila <sanvila@debian.org>
Originator: Person: Santiago Vila <sanvila@debian.org>
"]
    style Package_cde4da818c0e9c49e351a818c63522c0 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_8346c4c73751a9401db8c46d28116490["[Package]
Name: dpkg
Version: 1.22.22
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Dpkg Developers <debian-dpkg@lists.debian.org>
Originator: Person: Dpkg Developers <debian-dpkg@lists.debian.org>
"]
    style Package_8346c4c73751a9401db8c46d28116490 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_869a1ff455854013d3f257360a154782["[Package]
Name: findutils
Version: 4.10.0-3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Andreas Metzler <ametzler@debian.org>
Originator: Person: Andreas Metzler <ametzler@debian.org>
"]
    style Package_869a1ff455854013d3f257360a154782 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_26ab7fa49a859230998e229455240cb5["[Package]
Name: gcc-14-base
Version: 14.2.0-19
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Originator: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
"]
    style Package_26ab7fa49a859230998e229455240cb5 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_7f7e7b711aaaa224d1ab3f6e22951c64["[Package]
Name: gcc-14
Version: 14.2.0-19
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Originator: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
"]
    style Package_7f7e7b711aaaa224d1ab3f6e22951c64 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_70d111e4a4352b659abb31378ed4f826["[Package]
Name: gdbm
Version: 1.24-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Nicolas Mora <babelouest@debian.org>
Originator: Person: Nicolas Mora <babelouest@debian.org>
"]
    style Package_70d111e4a4352b659abb31378ed4f826 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_68ed8966865bee340e50e3cffefe9c38["[Package]
Name: glibc
Version: 2.41-12+deb13u2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Originator: Person: GNU Libc Maintainers <debian-glibc@lists.debian.org>
"]
    style Package_68ed8966865bee340e50e3cffefe9c38 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_d71fcd6c8105140a776255c3d6a91e66["[Package]
Name: gmp
Version: 2:6.3.0+dfsg-3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Originator: Person: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
"]
    style Package_d71fcd6c8105140a776255c3d6a91e66 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_17442d01b663d1cfe900db535316fe9c["[Package]
Name: grep
Version: 3.11-4+b1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Anibal Monsalve Salazar <anibal@debian.org>
Originator: Person: Anibal Monsalve Salazar <anibal@debian.org>
"]
    style Package_17442d01b663d1cfe900db535316fe9c fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_304e1659b44ec6f7482e7e4e4f3850f7["[Package]
Name: gzip
Version: 1.13-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Milan Kupcevic <milan@debian.org>
Originator: Person: Milan Kupcevic <milan@debian.org>
"]
    style Package_304e1659b44ec6f7482e7e4e4f3850f7 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_349f1ff89a2b95019eaf0a1e08d5687f["[Package]
Name: hostname
Version: 3.25
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Michael Meskes <meskes@debian.org>
Originator: Person: Michael Meskes <meskes@debian.org>
"]
    style Package_349f1ff89a2b95019eaf0a1e08d5687f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_1affcc4058a3c992c9f585e296888d5d["[Package]
Name: init-system-helpers
Version: 1.69~deb13u1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
Originator: Person: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
"]
    style Package_1affcc4058a3c992c9f585e296888d5d fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_d09926acae3d2b8539232c2a1c3cd828["[Package]
Name: libacl1
Version: 2.3.2-2+b1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Guillem Jover <guillem@debian.org>
Originator: Person: Guillem Jover <guillem@debian.org>
"]
    style Package_d09926acae3d2b8539232c2a1c3cd828 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_1eafa4076f47a7631e34a0eb9fe0890e["[Package]
Name: libapt-pkg7.0
Version: 3.0.3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: APT Development Team <deity@lists.debian.org>
Originator: Person: APT Development Team <deity@lists.debian.org>
"]
    style Package_1eafa4076f47a7631e34a0eb9fe0890e fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_24b6135493750eab7330a4a6fb1db47f["[Package]
Name: libattr1
Version: 1:2.5.2-3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Guillem Jover <guillem@debian.org>
Originator: Person: Guillem Jover <guillem@debian.org>
"]
    style Package_24b6135493750eab7330a4a6fb1db47f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_0e786341b5504531329ce5bcb5f9799b["[Package]
Name: libaudit-common
Version: 1:4.0.2-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Laurent Bigonville <bigon@debian.org>
Originator: Person: Laurent Bigonville <bigon@debian.org>
"]
    style Package_0e786341b5504531329ce5bcb5f9799b fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_204e999a4b7a3603dcfc48b5e9babece["[Package]
Name: libaudit1
Version: 1:4.0.2-2+b2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Laurent Bigonville <bigon@debian.org>
Originator: Person: Laurent Bigonville <bigon@debian.org>
"]
    style Package_204e999a4b7a3603dcfc48b5e9babece fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_e6b57feebc3197ef064819224b36a54e["[Package]
Name: libblkid1
Version: 2.41-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Chris Hofstaedtler <zeha@debian.org>
Originator: Person: Chris Hofstaedtler <zeha@debian.org>
"]
    style Package_e6b57feebc3197ef064819224b36a54e fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_7acf1809036e5d1e1db43f4702373af1["[Package]
Name: libbsd0
Version: 0.12.2-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Guillem Jover <guillem@debian.org>
Originator: Person: Guillem Jover <guillem@debian.org>
"]
    style Package_7acf1809036e5d1e1db43f4702373af1 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_05fa858ed0667a419713313cb4524f24["[Package]
Name: libbsd
Version: 0.12.2-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Guillem Jover <guillem@debian.org>
Originator: Person: Guillem Jover <guillem@debian.org>
"]
    style Package_05fa858ed0667a419713313cb4524f24 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_37c5d908ac1f02b5bd07591a6d352d35["[Package]
Name: libbz2-1.0
Version: 1.0.8-6
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Anibal Monsalve Salazar <anibal@debian.org>
Originator: Person: Anibal Monsalve Salazar <anibal@debian.org>
"]
    style Package_37c5d908ac1f02b5bd07591a6d352d35 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_15a58c139f188456feebb82bdbd4fa78["[Package]
Name: libc-bin
Version: 2.41-12+deb13u2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Originator: Person: GNU Libc Maintainers <debian-glibc@lists.debian.org>
"]
    style Package_15a58c139f188456feebb82bdbd4fa78 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_494c4af928eeacece08f4c3b32d18695["[Package]
Name: libc6
Version: 2.41-12+deb13u2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Originator: Person: GNU Libc Maintainers <debian-glibc@lists.debian.org>
"]
    style Package_494c4af928eeacece08f4c3b32d18695 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_db9759b70955975b4d673703a946ee03["[Package]
Name: libcap-ng0
Version: 0.8.5-4+b1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Håvard F. Aasen <havard.f.aasen@pfft.no>
Originator: Person: Håvard F. Aasen <havard.f.aasen@pfft.no>
"]
    style Package_db9759b70955975b4d673703a946ee03 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_d8a81eed5a6f1a08658a9911cbd417bd["[Package]
Name: libcap-ng
Version: 0.8.5-4
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Håvard F. Aasen <havard.f.aasen@pfft.no>
Originator: Person: Håvard F. Aasen <havard.f.aasen@pfft.no>
"]
    style Package_d8a81eed5a6f1a08658a9911cbd417bd fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_0639f79ff3ebaf9b812d46ec52bd016f["[Package]
Name: libcap2
Version: 1:2.75-10+b8
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Christian Kastner <ckk@debian.org>
Originator: Person: Christian Kastner <ckk@debian.org>
"]
    style Package_0639f79ff3ebaf9b812d46ec52bd016f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_8341623ee4bae47746631f18ceda8c57["[Package]
Name: libcrypt1
Version: 1:4.4.38-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Marco d'Itri <md@linux.it>
Originator: Person: Marco d'Itri <md@linux.it>
"]
    style Package_8341623ee4bae47746631f18ceda8c57 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_ae19ac1d15bda68c4aa5e90461209251["[Package]
Name: libdb5.3t64
Version: 5.3.28+dfsg2-9
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian QA Group <packages@qa.debian.org>
Originator: Person: Debian QA Group <packages@qa.debian.org>
"]
    style Package_ae19ac1d15bda68c4aa5e90461209251 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_949fdc9e8d9ab05ba7eca0b9de042b61["[Package]
Name: libdebconfclient0
Version: 0.280
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian Install System Team <debian-boot@lists.debian.org>
Originator: Person: Debian Install System Team <debian-boot@lists.debian.org>
"]
    style Package_949fdc9e8d9ab05ba7eca0b9de042b61 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_468d9f9f055a951e0a6695b99450f166["[Package]
Name: libffi8
Version: 3.4.8-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Originator: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
"]
    style Package_468d9f9f055a951e0a6695b99450f166 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_d6b2335fd91c0556d1f07350a7c062c2["[Package]
Name: libffi
Version: 3.4.8-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Originator: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
"]
    style Package_d6b2335fd91c0556d1f07350a7c062c2 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_7757e41348fbb4eb165d971e24aefb74["[Package]
Name: libgcc-s1
Version: 14.2.0-19
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Originator: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
"]
    style Package_7757e41348fbb4eb165d971e24aefb74 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_39843aff338b820e0aad683ec8f13f07["[Package]
Name: libgdbm6t64
Version: 1.24-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Nicolas Mora <babelouest@debian.org>
Originator: Person: Nicolas Mora <babelouest@debian.org>
"]
    style Package_39843aff338b820e0aad683ec8f13f07 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_48ba69ad745be2c92c48b2486359ec99["[Package]
Name: libgmp10
Version: 2:6.3.0+dfsg-3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
Originator: Person: Debian Science Maintainers <debian-science-maintainers@lists.alioth.debian.org>
"]
    style Package_48ba69ad745be2c92c48b2486359ec99 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_c5a9e256ad282929551b3915013fc38c["[Package]
Name: libhogweed6t64
Version: 3.10.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Magnus Holmgren <holmgren@debian.org>
Originator: Person: Magnus Holmgren <holmgren@debian.org>
"]
    style Package_c5a9e256ad282929551b3915013fc38c fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_3c8af6c2c6192d7026527ea9e715026e["[Package]
Name: liblastlog2-2
Version: 2.41-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Chris Hofstaedtler <zeha@debian.org>
Originator: Person: Chris Hofstaedtler <zeha@debian.org>
"]
    style Package_3c8af6c2c6192d7026527ea9e715026e fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_40dc8ad2d3f1c0d51d83ce2cb7275097["[Package]
Name: liblz4-1
Version: 1.10.0-4
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Nobuhiro Iwamatsu <iwamatsu@debian.org>
Originator: Person: Nobuhiro Iwamatsu <iwamatsu@debian.org>
"]
    style Package_40dc8ad2d3f1c0d51d83ce2cb7275097 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_0d22b34f88d505664fd6421511201263["[Package]
Name: liblzma5
Version: 5.8.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>
Originator: Person: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>
"]
    style Package_0d22b34f88d505664fd6421511201263 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_e60638ed22baa7feec132360952543d2["[Package]
Name: libmd0
Version: 1.1.0-2+b1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Guillem Jover <guillem@debian.org>
Originator: Person: Guillem Jover <guillem@debian.org>
"]
    style Package_e60638ed22baa7feec132360952543d2 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_d37f35e75540324e214bb7b269c616a7["[Package]
Name: libmd
Version: 1.1.0-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Guillem Jover <guillem@debian.org>
Originator: Person: Guillem Jover <guillem@debian.org>
"]
    style Package_d37f35e75540324e214bb7b269c616a7 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_b16b30fb23a4060fa6719111206f60ef["[Package]
Name: libmount1
Version: 2.41-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Chris Hofstaedtler <zeha@debian.org>
Originator: Person: Chris Hofstaedtler <zeha@debian.org>
"]
    style Package_b16b30fb23a4060fa6719111206f60ef fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_d3844c290584d158fda1b93bfad5ca6f["[Package]
Name: libncursesw6
Version: 6.5+20250216-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Ncurses Maintainers <ncurses@packages.debian.org>
Originator: Person: Ncurses Maintainers <ncurses@packages.debian.org>
"]
    style Package_d3844c290584d158fda1b93bfad5ca6f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_bdc18f92cd0da6f5083d2ceea4a85cdd["[Package]
Name: libnettle8t64
Version: 3.10.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Magnus Holmgren <holmgren@debian.org>
Originator: Person: Magnus Holmgren <holmgren@debian.org>
"]
    style Package_bdc18f92cd0da6f5083d2ceea4a85cdd fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_2b9c01a24f96bc991c70c07b0b288e1a["[Package]
Name: libpam-modules-bin
Version: 1.7.0-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Sam Hartman <hartmans@debian.org>
Originator: Person: Sam Hartman <hartmans@debian.org>
"]
    style Package_2b9c01a24f96bc991c70c07b0b288e1a fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_e2fad71055ba2ac1079c725aa4d5b42c["[Package]
Name: libpam-modules
Version: 1.7.0-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Sam Hartman <hartmans@debian.org>
Originator: Person: Sam Hartman <hartmans@debian.org>
"]
    style Package_e2fad71055ba2ac1079c725aa4d5b42c fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_4755d2e4fb2b18e8f9257e194b90a8c5["[Package]
Name: libpam-runtime
Version: 1.7.0-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Sam Hartman <hartmans@debian.org>
Originator: Person: Sam Hartman <hartmans@debian.org>
"]
    style Package_4755d2e4fb2b18e8f9257e194b90a8c5 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_f635b3896bb566b3bfbf852953aaa416["[Package]
Name: libpam0g
Version: 1.7.0-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Sam Hartman <hartmans@debian.org>
Originator: Person: Sam Hartman <hartmans@debian.org>
"]
    style Package_f635b3896bb566b3bfbf852953aaa416 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_17d2aaa0d2cf65672f738487ea49e282["[Package]
Name: libpcre2-8-0
Version: 10.46-1~deb13u1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Matthew Vernon <matthew@debian.org>
Originator: Person: Matthew Vernon <matthew@debian.org>
"]
    style Package_17d2aaa0d2cf65672f738487ea49e282 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_1c147f8b550f2121cff5de2da8b2166a["[Package]
Name: libreadline8t64
Version: 8.2-6
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Matthias Klose <doko@debian.org>
Originator: Person: Matthias Klose <doko@debian.org>
"]
    style Package_1c147f8b550f2121cff5de2da8b2166a fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_f61e7cd4f523785e846a81f3721fcc51["[Package]
Name: libseccomp2
Version: 2.6.0-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Kees Cook <kees@debian.org>
Originator: Person: Kees Cook <kees@debian.org>
"]
    style Package_f61e7cd4f523785e846a81f3721fcc51 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_3288b671e27cd591730d3c825fbffe28["[Package]
Name: libseccomp
Version: 2.6.0-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Kees Cook <kees@debian.org>
Originator: Person: Kees Cook <kees@debian.org>
"]
    style Package_3288b671e27cd591730d3c825fbffe28 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_d1a0d2ee4302634368ffdc589b051d62["[Package]
Name: libselinux1
Version: 3.8.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
Originator: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
"]
    style Package_d1a0d2ee4302634368ffdc589b051d62 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_f58852f5537d4e85667d6dc362c1dbd0["[Package]
Name: libselinux
Version: 3.8.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
Originator: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
"]
    style Package_f58852f5537d4e85667d6dc362c1dbd0 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_51840d28384be8f75270e4324997a514["[Package]
Name: libsemanage-common
Version: 3.8.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
Originator: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
"]
    style Package_51840d28384be8f75270e4324997a514 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_36f5ae8417ac9a47d149d7741d9b1287["[Package]
Name: libsemanage2
Version: 3.8.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
Originator: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
"]
    style Package_36f5ae8417ac9a47d149d7741d9b1287 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_0ef8bdb0a9aba50f238b4e932dc45b89["[Package]
Name: libsemanage
Version: 3.8.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
Originator: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
"]
    style Package_0ef8bdb0a9aba50f238b4e932dc45b89 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_c08052a2d4b6c54d99f1533b46d4bd28["[Package]
Name: libsepol2
Version: 3.8.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
Originator: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
"]
    style Package_c08052a2d4b6c54d99f1533b46d4bd28 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_58d568dec02f159a4dcf45662c75c5a2["[Package]
Name: libsepol
Version: 3.8.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
Originator: Person: Debian SELinux maintainers <selinux-devel@lists.alioth.debian.org>
"]
    style Package_58d568dec02f159a4dcf45662c75c5a2 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_79a12a2652b7e5a906c6d73064ec4ce5["[Package]
Name: libsmartcols1
Version: 2.41-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Chris Hofstaedtler <zeha@debian.org>
Originator: Person: Chris Hofstaedtler <zeha@debian.org>
"]
    style Package_79a12a2652b7e5a906c6d73064ec4ce5 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_b07bf35e19d30d52d160ced0ba5e7297["[Package]
Name: libsqlite3-0
Version: 3.46.1-7+deb13u1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Originator: Person: Laszlo Boszormenyi (GCS) <gcs@debian.org>
"]
    style Package_b07bf35e19d30d52d160ced0ba5e7297 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_2125d51c5fcf478bebdd94c527da6934["[Package]
Name: libssl3t64
Version: 3.5.5-1~deb13u2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian OpenSSL Team <pkg-openssl-devel@alioth-lists.debian.net>
Originator: Person: Debian OpenSSL Team <pkg-openssl-devel@alioth-lists.debian.net>
"]
    style Package_2125d51c5fcf478bebdd94c527da6934 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_5bb59cc08e09d2d13581a4d6a603a8dd["[Package]
Name: libstdc++6
Version: 14.2.0-19
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Originator: Person: Debian GCC Maintainers <debian-gcc@lists.debian.org>
"]
    style Package_5bb59cc08e09d2d13581a4d6a603a8dd fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_75c969fd64c908a6587692b3aa9b58de["[Package]
Name: libsystemd0
Version: 257.9-1~deb13u1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
Originator: Person: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
"]
    style Package_75c969fd64c908a6587692b3aa9b58de fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_9e3acb9bd967a963b2b0956a83e4879d["[Package]
Name: libtinfo6
Version: 6.5+20250216-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Ncurses Maintainers <ncurses@packages.debian.org>
Originator: Person: Ncurses Maintainers <ncurses@packages.debian.org>
"]
    style Package_9e3acb9bd967a963b2b0956a83e4879d fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_a4579486a3fa1e1e60da1bdfccf3d17d["[Package]
Name: libudev1
Version: 257.9-1~deb13u1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
Originator: Person: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
"]
    style Package_a4579486a3fa1e1e60da1bdfccf3d17d fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_56644af365cb2702904c1426efb165de["[Package]
Name: libuuid1
Version: 2.41-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Chris Hofstaedtler <zeha@debian.org>
Originator: Person: Chris Hofstaedtler <zeha@debian.org>
"]
    style Package_56644af365cb2702904c1426efb165de fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_cb4eefb88ee7e7cb40918d848299286f["[Package]
Name: libxcrypt
Version: 1:4.4.38-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Marco d'Itri <md@linux.it>
Originator: Person: Marco d'Itri <md@linux.it>
"]
    style Package_cb4eefb88ee7e7cb40918d848299286f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_eb12cc362f1bad39d9b18796a4e64c8a["[Package]
Name: libxxhash0
Version: 0.8.3-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Josue Ortega <josue@debian.org>
Originator: Person: Josue Ortega <josue@debian.org>
"]
    style Package_eb12cc362f1bad39d9b18796a4e64c8a fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_e56f5a900043acad2268b5e7258ef4fc["[Package]
Name: libzstd1
Version: 1.5.7+dfsg-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: RPM packaging team <team+pkg-rpm@tracker.debian.org>
Originator: Person: RPM packaging team <team+pkg-rpm@tracker.debian.org>
"]
    style Package_e56f5a900043acad2268b5e7258ef4fc fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_98a1a0dc5f1ccffceedb4e80f6538d39["[Package]
Name: libzstd
Version: 1.5.7+dfsg-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: RPM packaging team <team+pkg-rpm@tracker.debian.org>
Originator: Person: RPM packaging team <team+pkg-rpm@tracker.debian.org>
"]
    style Package_98a1a0dc5f1ccffceedb4e80f6538d39 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_df64415e6efeffe8406d3498bcfd2efc["[Package]
Name: login.defs
Version: 1:4.17.4-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Shadow package maintainers <pkg-shadow-devel@lists.alioth.debian.org>
Originator: Person: Shadow package maintainers <pkg-shadow-devel@lists.alioth.debian.org>
"]
    style Package_df64415e6efeffe8406d3498bcfd2efc fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_05d3b3f48a753cd61e4b021d47a22860["[Package]
Name: login
Version: 1:4.16.0-2+really2.41-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Chris Hofstaedtler <zeha@debian.org>
Originator: Person: Chris Hofstaedtler <zeha@debian.org>
"]
    style Package_05d3b3f48a753cd61e4b021d47a22860 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_2b601c6a0e86e80fea172ec2d083c246["[Package]
Name: lz4
Version: 1.10.0-4
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Nobuhiro Iwamatsu <iwamatsu@debian.org>
Originator: Person: Nobuhiro Iwamatsu <iwamatsu@debian.org>
"]
    style Package_2b601c6a0e86e80fea172ec2d083c246 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_adc2ae95963d9b9aeaf99d73d6bda1c0["[Package]
Name: mawk
Version: 1.3.4.20250131-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Boyuan Yang <byang@debian.org>
Originator: Person: Boyuan Yang <byang@debian.org>
"]
    style Package_adc2ae95963d9b9aeaf99d73d6bda1c0 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_6f38145d0a8c5e6470fd70ec0de4d211["[Package]
Name: mount
Version: 2.41-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Chris Hofstaedtler <zeha@debian.org>
Originator: Person: Chris Hofstaedtler <zeha@debian.org>
"]
    style Package_6f38145d0a8c5e6470fd70ec0de4d211 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_d7e0be9a80ac513a19c68bfa4cfab6da["[Package]
Name: ncurses-base
Version: 6.5+20250216-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Ncurses Maintainers <ncurses@packages.debian.org>
Originator: Person: Ncurses Maintainers <ncurses@packages.debian.org>
"]
    style Package_d7e0be9a80ac513a19c68bfa4cfab6da fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_f10dd27e0a7c860d3d51a2bab554c575["[Package]
Name: ncurses-bin
Version: 6.5+20250216-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Ncurses Maintainers <ncurses@packages.debian.org>
Originator: Person: Ncurses Maintainers <ncurses@packages.debian.org>
"]
    style Package_f10dd27e0a7c860d3d51a2bab554c575 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_94e1206f70525f46db46e865c625226a["[Package]
Name: ncurses
Version: 6.5+20250216-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Ncurses Maintainers <ncurses@packages.debian.org>
Originator: Person: Ncurses Maintainers <ncurses@packages.debian.org>
"]
    style Package_94e1206f70525f46db46e865c625226a fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_cd14592debfcfd5466962482d3c648bf["[Package]
Name: netbase
Version: 6.5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Marco d'Itri <md@linux.it>
Originator: Person: Marco d'Itri <md@linux.it>
"]
    style Package_cd14592debfcfd5466962482d3c648bf fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_9b06a5d701a2dc4169712ed7e2066c65["[Package]
Name: nettle
Version: 3.10.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Magnus Holmgren <holmgren@debian.org>
Originator: Person: Magnus Holmgren <holmgren@debian.org>
"]
    style Package_9b06a5d701a2dc4169712ed7e2066c65 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_05ddc2e1815a825c594767d32c772e37["[Package]
Name: openssl-provider-legacy
Version: 3.5.5-1~deb13u2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian OpenSSL Team <pkg-openssl-devel@alioth-lists.debian.net>
Originator: Person: Debian OpenSSL Team <pkg-openssl-devel@alioth-lists.debian.net>
"]
    style Package_05ddc2e1815a825c594767d32c772e37 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_7a951f60f30b7b471fdd6b15a5b0f2b6["[Package]
Name: openssl
Version: 3.5.5-1~deb13u2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian OpenSSL Team <pkg-openssl-devel@alioth-lists.debian.net>
Originator: Person: Debian OpenSSL Team <pkg-openssl-devel@alioth-lists.debian.net>
"]
    style Package_7a951f60f30b7b471fdd6b15a5b0f2b6 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_df9be288a38e8fef45ce5cbffda05d3a["[Package]
Name: pam
Version: 1.7.0-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Sam Hartman <hartmans@debian.org>
Originator: Person: Sam Hartman <hartmans@debian.org>
"]
    style Package_df9be288a38e8fef45ce5cbffda05d3a fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_ec48f1546ec934252547fbb776fc8afd["[Package]
Name: passwd
Version: 1:4.17.4-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Shadow package maintainers <pkg-shadow-devel@lists.alioth.debian.org>
Originator: Person: Shadow package maintainers <pkg-shadow-devel@lists.alioth.debian.org>
"]
    style Package_ec48f1546ec934252547fbb776fc8afd fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_6d455ad9d48fc599fb81ea78f6c4bc13["[Package]
Name: pcre2
Version: 10.46-1~deb13u1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Matthew Vernon <matthew@debian.org>
Originator: Person: Matthew Vernon <matthew@debian.org>
"]
    style Package_6d455ad9d48fc599fb81ea78f6c4bc13 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_a834bc8fafa2435695e8d58c66be9039["[Package]
Name: perl-base
Version: 5.40.1-6
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Niko Tyni <ntyni@debian.org>
Originator: Person: Niko Tyni <ntyni@debian.org>
"]
    style Package_a834bc8fafa2435695e8d58c66be9039 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_894bc102a72a7decd42d26c33719ae20["[Package]
Name: perl
Version: 5.40.1-6
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Niko Tyni <ntyni@debian.org>
Originator: Person: Niko Tyni <ntyni@debian.org>
"]
    style Package_894bc102a72a7decd42d26c33719ae20 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_f5cc69ee4bd01356845109ecbddb0588["[Package]
Name: readline-common
Version: 8.2-6
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Matthias Klose <doko@debian.org>
Originator: Person: Matthias Klose <doko@debian.org>
"]
    style Package_f5cc69ee4bd01356845109ecbddb0588 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_7aa2e0bfbc34096e1320068ecdc27679["[Package]
Name: readline
Version: 8.2-6
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Matthias Klose <doko@debian.org>
Originator: Person: Matthias Klose <doko@debian.org>
"]
    style Package_7aa2e0bfbc34096e1320068ecdc27679 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_7ed7ec2eb9aa83ec81ef0457ec0b3213["[Package]
Name: rust-sequoia-sqv
Version: 1.3.0-3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian Rust Maintainers <pkg-rust-maintainers@alioth-lists.debian.net>
Originator: Person: Debian Rust Maintainers <pkg-rust-maintainers@alioth-lists.debian.net>
"]
    style Package_7ed7ec2eb9aa83ec81ef0457ec0b3213 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_1e6d074839c66ed07ca77b04f55c2cae["[Package]
Name: sed
Version: 4.9-2+b1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Clint Adams <clint@debian.org>
Originator: Person: Clint Adams <clint@debian.org>
"]
    style Package_1e6d074839c66ed07ca77b04f55c2cae fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_4ac6b4d63150802b6b44793088a3fd51["[Package]
Name: shadow
Version: 1:4.17.4-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Shadow package maintainers <pkg-shadow-devel@lists.alioth.debian.org>
Originator: Person: Shadow package maintainers <pkg-shadow-devel@lists.alioth.debian.org>
"]
    style Package_4ac6b4d63150802b6b44793088a3fd51 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_b2c2173c36b275dd4701ed9889325b6d["[Package]
Name: sqlite3
Version: 3.46.1-7+deb13u1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Originator: Person: Laszlo Boszormenyi (GCS) <gcs@debian.org>
"]
    style Package_b2c2173c36b275dd4701ed9889325b6d fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_f5167d4f8ef0a2d3cd4bc8876f8f2e4a["[Package]
Name: sqv
Version: 1.3.0-3+b2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian Rust Maintainers <pkg-rust-maintainers@alioth-lists.debian.net>
Originator: Person: Debian Rust Maintainers <pkg-rust-maintainers@alioth-lists.debian.net>
"]
    style Package_f5167d4f8ef0a2d3cd4bc8876f8f2e4a fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_aae09e1686b924f2798c9216df4f33c6["[Package]
Name: systemd
Version: 257.9-1~deb13u1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
Originator: Person: Debian systemd Maintainers <pkg-systemd-maintainers@lists.alioth.debian.org>
"]
    style Package_aae09e1686b924f2798c9216df4f33c6 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_cc5987b162950271528456cefbef2354["[Package]
Name: sysvinit-utils
Version: 3.14-4
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian sysvinit maintainers <debian-init-diversity@chiark.greenend.org.uk>
Originator: Person: Debian sysvinit maintainers <debian-init-diversity@chiark.greenend.org.uk>
"]
    style Package_cc5987b162950271528456cefbef2354 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_b93822c63ad7944986d18ad15fb6d115["[Package]
Name: sysvinit
Version: 3.14-4
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Debian sysvinit maintainers <debian-init-diversity@chiark.greenend.org.uk>
Originator: Person: Debian sysvinit maintainers <debian-init-diversity@chiark.greenend.org.uk>
"]
    style Package_b93822c63ad7944986d18ad15fb6d115 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_50409e283c60292ab0e370d790c263dc["[Package]
Name: tar
Version: 1.35+dfsg-3.1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Janos Lenart <ocsi@debian.org>
Originator: Person: Janos Lenart <ocsi@debian.org>
"]
    style Package_50409e283c60292ab0e370d790c263dc fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_b8a51e976ead8c71868bbf9b3a47b3ba["[Package]
Name: tzdata
Version: 2026a-0+deb13u1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: GNU Libc Maintainers <debian-glibc@lists.debian.org>
Originator: Person: GNU Libc Maintainers <debian-glibc@lists.debian.org>
"]
    style Package_b8a51e976ead8c71868bbf9b3a47b3ba fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_d4e1cfd78cac5756637edc77891b92db["[Package]
Name: util-linux
Version: 2.41-5
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Chris Hofstaedtler <zeha@debian.org>
Originator: Person: Chris Hofstaedtler <zeha@debian.org>
"]
    style Package_d4e1cfd78cac5756637edc77891b92db fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_40bceca5070cfa30065766d28046a71e["[Package]
Name: xxhash
Version: 0.8.3-2
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Josue Ortega <josue@debian.org>
Originator: Person: Josue Ortega <josue@debian.org>
"]
    style Package_40bceca5070cfa30065766d28046a71e fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_6fe9116dcec0977843a00c19b1c5f23b["[Package]
Name: xz-utils
Version: 5.8.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>
Originator: Person: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>
"]
    style Package_6fe9116dcec0977843a00c19b1c5f23b fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_cf112f620a801e8e350730dfde3c4a7b["[Package]
Name: zlib1g
Version: 1:1.3.dfsg+really1.3.1-1+b1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Mark Brown <broonie@debian.org>
Originator: Person: Mark Brown <broonie@debian.org>
"]
    style Package_cf112f620a801e8e350730dfde3c4a7b fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_2ba1d3a7661da39ebdc1eab62057f403["[Package]
Name: zlib
Version: 1:1.3.dfsg+really1.3.1-1
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Mark Brown <broonie@debian.org>
Originator: Person: Mark Brown <broonie@debian.org>
"]
    style Package_2ba1d3a7661da39ebdc1eab62057f403 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_2334b4842904d66e300d60b7c9563524["[Package]
Name: python
Version: 3.13.13
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_2334b4842904d66e300d60b7c9563524 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_add2afb83a113e3ce773973a359d6f92["[Package]
Name: annotated-doc
Version: 0.0.4
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_add2afb83a113e3ce773973a359d6f92 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_07d4dc367635faf53a7811cc52b8fab7["[Package]
Name: annotated-types
Version: 0.7.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_07d4dc367635faf53a7811cc52b8fab7 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_ad67babaf9fafbde959fbee9dfb06682["[Package]
Name: anthropic
Version: 0.95.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_ad67babaf9fafbde959fbee9dfb06682 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_f7e43d706b3e58000d9e39ee4ad611aa["[Package]
Name: anyio
Version: 4.13.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_f7e43d706b3e58000d9e39ee4ad611aa fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_b6814eb4a7233e13fc3d9d6ab5e1e69c["[Package]
Name: certifi
Version: 2026.2.25
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Kenneth Reitz
Originator: Person: Kenneth Reitz
"]
    style Package_b6814eb4a7233e13fc3d9d6ab5e1e69c fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_4cfa07339d773dbb828bdee9f3e70809["[Package]
Name: click
Version: 8.3.2
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_4cfa07339d773dbb828bdee9f3e70809 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_0988e4eefeede4115687955491d975af["[Package]
Name: distro
Version: 1.9.0
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Nir Cohen
Originator: Person: Nir Cohen
"]
    style Package_0988e4eefeede4115687955491d975af fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_52b85408420e17015828e90989fb4157["[Package]
Name: docstring-parser
Version: 0.18.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_52b85408420e17015828e90989fb4157 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_60cd127b4a8a960c1fd77d03dfed6d16["[Package]
Name: fastapi
Version: 0.135.3
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_60cd127b4a8a960c1fd77d03dfed6d16 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_9e2897abcb3d777439c7a3fba979efbd["[Package]
Name: greenlet
Version: 3.4.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_9e2897abcb3d777439c7a3fba979efbd fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_391c219ed2c134d5525e3a25879b1f69["[Package]
Name: h11
Version: 0.16.0
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Nathaniel J. Smith
Originator: Person: Nathaniel J. Smith
"]
    style Package_391c219ed2c134d5525e3a25879b1f69 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_53e7aae9f6ffa6a408ab4dcc3ecae532["[Package]
Name: httpcore
Version: 1.0.9
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_53e7aae9f6ffa6a408ab4dcc3ecae532 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_602d775dcb54b797a220cfbeba6bc035["[Package]
Name: httptools
Version: 0.7.1
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_602d775dcb54b797a220cfbeba6bc035 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_68592761cb097ba599d8a88a359cd11b["[Package]
Name: httpx
Version: 0.28.1
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_68592761cb097ba599d8a88a359cd11b fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_604ce864f1f6e8956d47b834e18d8f3c["[Package]
Name: idna
Version: 3.11
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_604ce864f1f6e8956d47b834e18d8f3c fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_0d542fd11b88104b47de3ce7584eb3e3["[Package]
Name: jinja2
Version: 3.1.6
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_0d542fd11b88104b47de3ce7584eb3e3 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_9015e64e5961ba58332667a14ba1043d["[Package]
Name: jiter
Version: 0.14.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_9015e64e5961ba58332667a14ba1043d fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_a492a2d2608c5f2e798c53959326f360["[Package]
Name: markupsafe
Version: 3.0.3
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_a492a2d2608c5f2e798c53959326f360 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_bd356e71f369d08e1959547ad863f36f["[Package]
Name: pip
Version: 26.0.1
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_bd356e71f369d08e1959547ad863f36f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_84614a065bb5e10f4bae8003dca8031f["[Package]
Name: psycopg-binary
Version: 3.3.3
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_84614a065bb5e10f4bae8003dca8031f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_b29b681f5512e791899deee36de0dc29["[Package]
Name: psycopg
Version: 3.3.3
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_b29b681f5512e791899deee36de0dc29 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_87c9c6551e35788f4a6d7ac660ebb98f["[Package]
Name: pydantic-core
Version: 2.46.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_87c9c6551e35788f4a6d7ac660ebb98f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_256633dac70bbf32d4e201385d95862c["[Package]
Name: pydantic-settings
Version: 2.13.1
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_256633dac70bbf32d4e201385d95862c fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_3e65682c5d1c0c171154431a12a32bb2["[Package]
Name: pydantic
Version: 2.13.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_3e65682c5d1c0c171154431a12a32bb2 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_c91b747d524da2adcf2c59efea0bdaa1["[Package]
Name: python-dotenv
Version: 1.2.2
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_c91b747d524da2adcf2c59efea0bdaa1 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_50a8e926ed032aac3e40f0d85af3b6bf["[Package]
Name: python-multipart
Version: 0.0.26
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_50a8e926ed032aac3e40f0d85af3b6bf fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_75493e85e4e44ddc4e0802fa4dd104e3["[Package]
Name: pyyaml
Version: 6.0.3
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Kirill Simonov
Originator: Person: Kirill Simonov
"]
    style Package_75493e85e4e44ddc4e0802fa4dd104e3 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_40d430dbab5fe330116abb7fab931ec1["[Package]
Name: sniffio
Version: 1.3.1
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_40d430dbab5fe330116abb7fab931ec1 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_5c91651cfbe344dd7e95f72bbc5d4020["[Package]
Name: sqlalchemy
Version: 2.0.49
License: NOASSERTION
Download: NOASSERTION
Supplier: Person: Mike Bayer
Originator: Person: Mike Bayer
"]
    style Package_5c91651cfbe344dd7e95f72bbc5d4020 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_27e63fc34fddd15b8da0505feb711e94["[Package]
Name: starlette
Version: 1.0.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_27e63fc34fddd15b8da0505feb711e94 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_2141d6d25a0fa345ff502e4ef11639a8["[Package]
Name: typing-extensions
Version: 4.15.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_2141d6d25a0fa345ff502e4ef11639a8 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_6b4b923e9a008347448ab30e3b1946b5["[Package]
Name: typing-inspection
Version: 0.4.2
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_6b4b923e9a008347448ab30e3b1946b5 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_db11823e6b5285c364c21ea94100df82["[Package]
Name: uvicorn
Version: 0.44.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_db11823e6b5285c364c21ea94100df82 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_ff47bc43d0cfec0cb7bd65e128e4788d["[Package]
Name: uvloop
Version: 0.22.1
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_ff47bc43d0cfec0cb7bd65e128e4788d fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_77c96e44610b62101d170f55315ce1bb["[Package]
Name: watchfiles
Version: 1.1.1
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_77c96e44610b62101d170f55315ce1bb fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_41d6596b72bf4420d51dadad2e00c83c["[Package]
Name: websockets
Version: 16.0
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_41d6596b72bf4420d51dadad2e00c83c fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_a4cfb3f047520ebceb18e7a26e16bd12["[Package]
Name: cyrus-sasl-lib
Version: 2.1.27-6.el8_5
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_a4cfb3f047520ebceb18e7a26e16bd12 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_90c71c5708b2baaa6960d4255c314f42["[Package]
Name: keyutils-libs
Version: 1.5.10-9.el8
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_90c71c5708b2baaa6960d4255c314f42 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_f011b6f3926afdb8033a5c38ba69247f["[Package]
Name: krb5-libs
Version: 1.18.2-32.el8_10
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_f011b6f3926afdb8033a5c38ba69247f fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_9192b6f786c4daaa4020e021a572146c["[Package]
Name: libcom_err
Version: 1.45.6-7.el8_10
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_9192b6f786c4daaa4020e021a572146c fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_a46f6c6e5587d1c52886d305b95deb02["[Package]
Name: libselinux
Version: 2.9-10.el8_10
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_a46f6c6e5587d1c52886d305b95deb02 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_e745a6a84ddaa84b4db118a88297b23e["[Package]
Name: libxcrypt
Version: 4.1.1-6.el8
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_e745a6a84ddaa84b4db118a88297b23e fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_4c6ccc98c76551e98a68ffc377691a27["[Package]
Name: openssl-libs
Version: 1.1.1k-14.el8_6
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_4c6ccc98c76551e98a68ffc377691a27 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    Package_023db9045e99003c2a8402060e07c571["[Package]
Name: pcre2
Version: 10.32-3.el8_6
License: NOASSERTION
Download: NOASSERTION
Supplier: NOASSERTION
Originator: NOASSERTION
"]
    style Package_023db9045e99003c2a8402060e07c571 fill:#f3e5f5,stroke:#4a148c,stroke-width:2px
    DOCUMENT -->|"DESCRIBES"| DocumentRoot
    DocumentRoot -->|"CONTAINS"| Package_93bd1c920854d3ea54091f1460ba6798
    DocumentRoot -->|"CONTAINS"| Package_fb24b66b7b1d9c53fe8f144a3c3c40e5
    DocumentRoot -->|"CONTAINS"| Package_02cbae335032e5670250f30772387493
    DocumentRoot -->|"CONTAINS"| Package_4071db2ba67968632ef80ba78a0aa74a
    DocumentRoot -->|"CONTAINS"| Package_1e8611cf6af09e2ddce30f997c8983bd
    DocumentRoot -->|"CONTAINS"| Package_f7f688f0ad52acae46bf3241a4425fb8
    DocumentRoot -->|"CONTAINS"| Package_2c3f88677ad431593367af04c038ea5b
    DocumentRoot -->|"CONTAINS"| Package_548d4a79f05a5a0daa8554f7ec815b8e
    DocumentRoot -->|"CONTAINS"| Package_e9d2db56123850a45082110662f48ee3
    DocumentRoot -->|"CONTAINS"| Package_c9fbb1e6159fd2f3708cd103cda4f593
    DocumentRoot -->|"CONTAINS"| Package_e74252795d7e73ea88f0c17bec3531e3
    DocumentRoot -->|"CONTAINS"| Package_81ff56ccef416310950723196baeabb9
    DocumentRoot -->|"CONTAINS"| Package_e06ca5ca1b19314aa5268c5a7e297742
    DocumentRoot -->|"CONTAINS"| Package_1e28e26d24b628f89a06f1dfdb406edb
    DocumentRoot -->|"CONTAINS"| Package_2bb6caac75a6f4cabfc0d78016a8ebe1
    DocumentRoot -->|"CONTAINS"| Package_5e0124d66015307aa6f05eb1be5f5ea9
    DocumentRoot -->|"CONTAINS"| Package_3cd69302188ba1aa89f1e2aef1a9bc2f
    DocumentRoot -->|"CONTAINS"| Package_8535194951c4cf118f18adb326161c72
    DocumentRoot -->|"CONTAINS"| Package_cde4da818c0e9c49e351a818c63522c0
    DocumentRoot -->|"CONTAINS"| Package_8346c4c73751a9401db8c46d28116490
    DocumentRoot -->|"CONTAINS"| Package_869a1ff455854013d3f257360a154782
    DocumentRoot -->|"CONTAINS"| Package_26ab7fa49a859230998e229455240cb5
    DocumentRoot -->|"CONTAINS"| Package_7f7e7b711aaaa224d1ab3f6e22951c64
    DocumentRoot -->|"CONTAINS"| Package_70d111e4a4352b659abb31378ed4f826
    DocumentRoot -->|"CONTAINS"| Package_68ed8966865bee340e50e3cffefe9c38
    DocumentRoot -->|"CONTAINS"| Package_d71fcd6c8105140a776255c3d6a91e66
    DocumentRoot -->|"CONTAINS"| Package_17442d01b663d1cfe900db535316fe9c
    DocumentRoot -->|"CONTAINS"| Package_304e1659b44ec6f7482e7e4e4f3850f7
    DocumentRoot -->|"CONTAINS"| Package_349f1ff89a2b95019eaf0a1e08d5687f
    DocumentRoot -->|"CONTAINS"| Package_1affcc4058a3c992c9f585e296888d5d
    DocumentRoot -->|"CONTAINS"| Package_d09926acae3d2b8539232c2a1c3cd828
    DocumentRoot -->|"CONTAINS"| Package_1eafa4076f47a7631e34a0eb9fe0890e
    DocumentRoot -->|"CONTAINS"| Package_24b6135493750eab7330a4a6fb1db47f
    DocumentRoot -->|"CONTAINS"| Package_0e786341b5504531329ce5bcb5f9799b
    DocumentRoot -->|"CONTAINS"| Package_204e999a4b7a3603dcfc48b5e9babece
    DocumentRoot -->|"CONTAINS"| Package_e6b57feebc3197ef064819224b36a54e
    DocumentRoot -->|"CONTAINS"| Package_7acf1809036e5d1e1db43f4702373af1
    DocumentRoot -->|"CONTAINS"| Package_05fa858ed0667a419713313cb4524f24
    DocumentRoot -->|"CONTAINS"| Package_37c5d908ac1f02b5bd07591a6d352d35
    DocumentRoot -->|"CONTAINS"| Package_15a58c139f188456feebb82bdbd4fa78
    DocumentRoot -->|"CONTAINS"| Package_494c4af928eeacece08f4c3b32d18695
    DocumentRoot -->|"CONTAINS"| Package_db9759b70955975b4d673703a946ee03
    DocumentRoot -->|"CONTAINS"| Package_d8a81eed5a6f1a08658a9911cbd417bd
    DocumentRoot -->|"CONTAINS"| Package_0639f79ff3ebaf9b812d46ec52bd016f
    DocumentRoot -->|"CONTAINS"| Package_8341623ee4bae47746631f18ceda8c57
    DocumentRoot -->|"CONTAINS"| Package_ae19ac1d15bda68c4aa5e90461209251
    DocumentRoot -->|"CONTAINS"| Package_949fdc9e8d9ab05ba7eca0b9de042b61
    DocumentRoot -->|"CONTAINS"| Package_468d9f9f055a951e0a6695b99450f166
    DocumentRoot -->|"CONTAINS"| Package_d6b2335fd91c0556d1f07350a7c062c2
    DocumentRoot -->|"CONTAINS"| Package_7757e41348fbb4eb165d971e24aefb74
    DocumentRoot -->|"CONTAINS"| Package_39843aff338b820e0aad683ec8f13f07
    DocumentRoot -->|"CONTAINS"| Package_48ba69ad745be2c92c48b2486359ec99
    DocumentRoot -->|"CONTAINS"| Package_c5a9e256ad282929551b3915013fc38c
    DocumentRoot -->|"CONTAINS"| Package_3c8af6c2c6192d7026527ea9e715026e
    DocumentRoot -->|"CONTAINS"| Package_40dc8ad2d3f1c0d51d83ce2cb7275097
    DocumentRoot -->|"CONTAINS"| Package_0d22b34f88d505664fd6421511201263
    DocumentRoot -->|"CONTAINS"| Package_e60638ed22baa7feec132360952543d2
    DocumentRoot -->|"CONTAINS"| Package_d37f35e75540324e214bb7b269c616a7
    DocumentRoot -->|"CONTAINS"| Package_b16b30fb23a4060fa6719111206f60ef
    DocumentRoot -->|"CONTAINS"| Package_d3844c290584d158fda1b93bfad5ca6f
    DocumentRoot -->|"CONTAINS"| Package_bdc18f92cd0da6f5083d2ceea4a85cdd
    DocumentRoot -->|"CONTAINS"| Package_2b9c01a24f96bc991c70c07b0b288e1a
    DocumentRoot -->|"CONTAINS"| Package_e2fad71055ba2ac1079c725aa4d5b42c
    DocumentRoot -->|"CONTAINS"| Package_4755d2e4fb2b18e8f9257e194b90a8c5
    DocumentRoot -->|"CONTAINS"| Package_f635b3896bb566b3bfbf852953aaa416
    DocumentRoot -->|"CONTAINS"| Package_17d2aaa0d2cf65672f738487ea49e282
    DocumentRoot -->|"CONTAINS"| Package_1c147f8b550f2121cff5de2da8b2166a
    DocumentRoot -->|"CONTAINS"| Package_f61e7cd4f523785e846a81f3721fcc51
    DocumentRoot -->|"CONTAINS"| Package_3288b671e27cd591730d3c825fbffe28
    DocumentRoot -->|"CONTAINS"| Package_d1a0d2ee4302634368ffdc589b051d62
    DocumentRoot -->|"CONTAINS"| Package_f58852f5537d4e85667d6dc362c1dbd0
    DocumentRoot -->|"CONTAINS"| Package_51840d28384be8f75270e4324997a514
    DocumentRoot -->|"CONTAINS"| Package_36f5ae8417ac9a47d149d7741d9b1287
    DocumentRoot -->|"CONTAINS"| Package_0ef8bdb0a9aba50f238b4e932dc45b89
    DocumentRoot -->|"CONTAINS"| Package_c08052a2d4b6c54d99f1533b46d4bd28
    DocumentRoot -->|"CONTAINS"| Package_58d568dec02f159a4dcf45662c75c5a2
    DocumentRoot -->|"CONTAINS"| Package_79a12a2652b7e5a906c6d73064ec4ce5
    DocumentRoot -->|"CONTAINS"| Package_b07bf35e19d30d52d160ced0ba5e7297
    DocumentRoot -->|"CONTAINS"| Package_2125d51c5fcf478bebdd94c527da6934
    DocumentRoot -->|"CONTAINS"| Package_5bb59cc08e09d2d13581a4d6a603a8dd
    DocumentRoot -->|"CONTAINS"| Package_75c969fd64c908a6587692b3aa9b58de
    DocumentRoot -->|"CONTAINS"| Package_9e3acb9bd967a963b2b0956a83e4879d
    DocumentRoot -->|"CONTAINS"| Package_a4579486a3fa1e1e60da1bdfccf3d17d
    DocumentRoot -->|"CONTAINS"| Package_56644af365cb2702904c1426efb165de
    DocumentRoot -->|"CONTAINS"| Package_cb4eefb88ee7e7cb40918d848299286f
    DocumentRoot -->|"CONTAINS"| Package_eb12cc362f1bad39d9b18796a4e64c8a
    DocumentRoot -->|"CONTAINS"| Package_e56f5a900043acad2268b5e7258ef4fc
    DocumentRoot -->|"CONTAINS"| Package_98a1a0dc5f1ccffceedb4e80f6538d39
    DocumentRoot -->|"CONTAINS"| Package_df64415e6efeffe8406d3498bcfd2efc
    DocumentRoot -->|"CONTAINS"| Package_05d3b3f48a753cd61e4b021d47a22860
    DocumentRoot -->|"CONTAINS"| Package_2b601c6a0e86e80fea172ec2d083c246
    DocumentRoot -->|"CONTAINS"| Package_adc2ae95963d9b9aeaf99d73d6bda1c0
    DocumentRoot -->|"CONTAINS"| Package_6f38145d0a8c5e6470fd70ec0de4d211
    DocumentRoot -->|"CONTAINS"| Package_d7e0be9a80ac513a19c68bfa4cfab6da
    DocumentRoot -->|"CONTAINS"| Package_f10dd27e0a7c860d3d51a2bab554c575
    DocumentRoot -->|"CONTAINS"| Package_94e1206f70525f46db46e865c625226a
    DocumentRoot -->|"CONTAINS"| Package_cd14592debfcfd5466962482d3c648bf
    DocumentRoot -->|"CONTAINS"| Package_9b06a5d701a2dc4169712ed7e2066c65
    DocumentRoot -->|"CONTAINS"| Package_05ddc2e1815a825c594767d32c772e37
    DocumentRoot -->|"CONTAINS"| Package_7a951f60f30b7b471fdd6b15a5b0f2b6
    DocumentRoot -->|"CONTAINS"| Package_df9be288a38e8fef45ce5cbffda05d3a
    DocumentRoot -->|"CONTAINS"| Package_ec48f1546ec934252547fbb776fc8afd
    DocumentRoot -->|"CONTAINS"| Package_6d455ad9d48fc599fb81ea78f6c4bc13
    DocumentRoot -->|"CONTAINS"| Package_a834bc8fafa2435695e8d58c66be9039
    DocumentRoot -->|"CONTAINS"| Package_894bc102a72a7decd42d26c33719ae20
    DocumentRoot -->|"CONTAINS"| Package_f5cc69ee4bd01356845109ecbddb0588
    DocumentRoot -->|"CONTAINS"| Package_7aa2e0bfbc34096e1320068ecdc27679
    DocumentRoot -->|"CONTAINS"| Package_7ed7ec2eb9aa83ec81ef0457ec0b3213
    DocumentRoot -->|"CONTAINS"| Package_1e6d074839c66ed07ca77b04f55c2cae
    DocumentRoot -->|"CONTAINS"| Package_4ac6b4d63150802b6b44793088a3fd51
    DocumentRoot -->|"CONTAINS"| Package_b2c2173c36b275dd4701ed9889325b6d
    DocumentRoot -->|"CONTAINS"| Package_f5167d4f8ef0a2d3cd4bc8876f8f2e4a
    DocumentRoot -->|"CONTAINS"| Package_aae09e1686b924f2798c9216df4f33c6
    DocumentRoot -->|"CONTAINS"| Package_cc5987b162950271528456cefbef2354
    DocumentRoot -->|"CONTAINS"| Package_b93822c63ad7944986d18ad15fb6d115
    DocumentRoot -->|"CONTAINS"| Package_50409e283c60292ab0e370d790c263dc
    DocumentRoot -->|"CONTAINS"| Package_b8a51e976ead8c71868bbf9b3a47b3ba
    DocumentRoot -->|"CONTAINS"| Package_d4e1cfd78cac5756637edc77891b92db
    DocumentRoot -->|"CONTAINS"| Package_40bceca5070cfa30065766d28046a71e
    DocumentRoot -->|"CONTAINS"| Package_6fe9116dcec0977843a00c19b1c5f23b
    DocumentRoot -->|"CONTAINS"| Package_cf112f620a801e8e350730dfde3c4a7b
    DocumentRoot -->|"CONTAINS"| Package_2ba1d3a7661da39ebdc1eab62057f403
    DocumentRoot -->|"CONTAINS"| Package_2334b4842904d66e300d60b7c9563524
    DocumentRoot -->|"CONTAINS"| Package_add2afb83a113e3ce773973a359d6f92
    DocumentRoot -->|"CONTAINS"| Package_07d4dc367635faf53a7811cc52b8fab7
    DocumentRoot -->|"CONTAINS"| Package_ad67babaf9fafbde959fbee9dfb06682
    DocumentRoot -->|"CONTAINS"| Package_f7e43d706b3e58000d9e39ee4ad611aa
    DocumentRoot -->|"CONTAINS"| Package_b6814eb4a7233e13fc3d9d6ab5e1e69c
    DocumentRoot -->|"CONTAINS"| Package_4cfa07339d773dbb828bdee9f3e70809
    DocumentRoot -->|"CONTAINS"| Package_0988e4eefeede4115687955491d975af
    DocumentRoot -->|"CONTAINS"| Package_52b85408420e17015828e90989fb4157
    DocumentRoot -->|"CONTAINS"| Package_60cd127b4a8a960c1fd77d03dfed6d16
    DocumentRoot -->|"CONTAINS"| Package_9e2897abcb3d777439c7a3fba979efbd
    DocumentRoot -->|"CONTAINS"| Package_391c219ed2c134d5525e3a25879b1f69
    DocumentRoot -->|"CONTAINS"| Package_53e7aae9f6ffa6a408ab4dcc3ecae532
    DocumentRoot -->|"CONTAINS"| Package_602d775dcb54b797a220cfbeba6bc035
    DocumentRoot -->|"CONTAINS"| Package_68592761cb097ba599d8a88a359cd11b
    DocumentRoot -->|"CONTAINS"| Package_604ce864f1f6e8956d47b834e18d8f3c
    DocumentRoot -->|"CONTAINS"| Package_0d542fd11b88104b47de3ce7584eb3e3
    DocumentRoot -->|"CONTAINS"| Package_9015e64e5961ba58332667a14ba1043d
    DocumentRoot -->|"CONTAINS"| Package_a492a2d2608c5f2e798c53959326f360
    DocumentRoot -->|"CONTAINS"| Package_bd356e71f369d08e1959547ad863f36f
    DocumentRoot -->|"CONTAINS"| Package_84614a065bb5e10f4bae8003dca8031f
    DocumentRoot -->|"CONTAINS"| Package_b29b681f5512e791899deee36de0dc29
    DocumentRoot -->|"CONTAINS"| Package_87c9c6551e35788f4a6d7ac660ebb98f
    DocumentRoot -->|"CONTAINS"| Package_256633dac70bbf32d4e201385d95862c
    DocumentRoot -->|"CONTAINS"| Package_3e65682c5d1c0c171154431a12a32bb2
    DocumentRoot -->|"CONTAINS"| Package_c91b747d524da2adcf2c59efea0bdaa1
    DocumentRoot -->|"CONTAINS"| Package_50a8e926ed032aac3e40f0d85af3b6bf
    DocumentRoot -->|"CONTAINS"| Package_75493e85e4e44ddc4e0802fa4dd104e3
    DocumentRoot -->|"CONTAINS"| Package_40d430dbab5fe330116abb7fab931ec1
    DocumentRoot -->|"CONTAINS"| Package_5c91651cfbe344dd7e95f72bbc5d4020
    DocumentRoot -->|"CONTAINS"| Package_27e63fc34fddd15b8da0505feb711e94
    DocumentRoot -->|"CONTAINS"| Package_2141d6d25a0fa345ff502e4ef11639a8
    DocumentRoot -->|"CONTAINS"| Package_6b4b923e9a008347448ab30e3b1946b5
    DocumentRoot -->|"CONTAINS"| Package_db11823e6b5285c364c21ea94100df82
    DocumentRoot -->|"CONTAINS"| Package_ff47bc43d0cfec0cb7bd65e128e4788d
    DocumentRoot -->|"CONTAINS"| Package_77c96e44610b62101d170f55315ce1bb
    DocumentRoot -->|"CONTAINS"| Package_41d6596b72bf4420d51dadad2e00c83c
    DocumentRoot -->|"CONTAINS"| Package_a4cfb3f047520ebceb18e7a26e16bd12
    DocumentRoot -->|"CONTAINS"| Package_90c71c5708b2baaa6960d4255c314f42
    DocumentRoot -->|"CONTAINS"| Package_f011b6f3926afdb8033a5c38ba69247f
    DocumentRoot -->|"CONTAINS"| Package_9192b6f786c4daaa4020e021a572146c
    DocumentRoot -->|"CONTAINS"| Package_a46f6c6e5587d1c52886d305b95deb02
    DocumentRoot -->|"CONTAINS"| Package_e745a6a84ddaa84b4db118a88297b23e
    DocumentRoot -->|"CONTAINS"| Package_4c6ccc98c76551e98a68ffc377691a27
    DocumentRoot -->|"CONTAINS"| Package_023db9045e99003c2a8402060e07c571
    Package_e9d2db56123850a45082110662f48ee3 -->|"GENERATED_FROM"| Package_d4e1cfd78cac5756637edc77891b92db
    Package_26ab7fa49a859230998e229455240cb5 -->|"GENERATED_FROM"| Package_7f7e7b711aaaa224d1ab3f6e22951c64
    Package_d09926acae3d2b8539232c2a1c3cd828 -->|"GENERATED_FROM"| Package_93bd1c920854d3ea54091f1460ba6798
    Package_1eafa4076f47a7631e34a0eb9fe0890e -->|"GENERATED_FROM"| Package_02cbae335032e5670250f30772387493
    Package_24b6135493750eab7330a4a6fb1db47f -->|"GENERATED_FROM"| Package_4071db2ba67968632ef80ba78a0aa74a
    Package_0e786341b5504531329ce5bcb5f9799b -->|"GENERATED_FROM"| Package_1e8611cf6af09e2ddce30f997c8983bd
    Package_204e999a4b7a3603dcfc48b5e9babece -->|"GENERATED_FROM"| Package_1e8611cf6af09e2ddce30f997c8983bd
    Package_e6b57feebc3197ef064819224b36a54e -->|"GENERATED_FROM"| Package_d4e1cfd78cac5756637edc77891b92db
    Package_7acf1809036e5d1e1db43f4702373af1 -->|"GENERATED_FROM"| Package_05fa858ed0667a419713313cb4524f24
    Package_37c5d908ac1f02b5bd07591a6d352d35 -->|"GENERATED_FROM"| Package_c9fbb1e6159fd2f3708cd103cda4f593
    Package_15a58c139f188456feebb82bdbd4fa78 -->|"GENERATED_FROM"| Package_68ed8966865bee340e50e3cffefe9c38
    Package_494c4af928eeacece08f4c3b32d18695 -->|"GENERATED_FROM"| Package_68ed8966865bee340e50e3cffefe9c38
    Package_db9759b70955975b4d673703a946ee03 -->|"GENERATED_FROM"| Package_d8a81eed5a6f1a08658a9911cbd417bd
    Package_8341623ee4bae47746631f18ceda8c57 -->|"GENERATED_FROM"| Package_cb4eefb88ee7e7cb40918d848299286f
    Package_ae19ac1d15bda68c4aa5e90461209251 -->|"GENERATED_FROM"| Package_2bb6caac75a6f4cabfc0d78016a8ebe1
    Package_949fdc9e8d9ab05ba7eca0b9de042b61 -->|"GENERATED_FROM"| Package_81ff56ccef416310950723196baeabb9
    Package_468d9f9f055a951e0a6695b99450f166 -->|"GENERATED_FROM"| Package_d6b2335fd91c0556d1f07350a7c062c2
    Package_7757e41348fbb4eb165d971e24aefb74 -->|"GENERATED_FROM"| Package_7f7e7b711aaaa224d1ab3f6e22951c64
    Package_39843aff338b820e0aad683ec8f13f07 -->|"GENERATED_FROM"| Package_70d111e4a4352b659abb31378ed4f826
    Package_48ba69ad745be2c92c48b2486359ec99 -->|"GENERATED_FROM"| Package_d71fcd6c8105140a776255c3d6a91e66
    Package_c5a9e256ad282929551b3915013fc38c -->|"GENERATED_FROM"| Package_9b06a5d701a2dc4169712ed7e2066c65
    Package_3c8af6c2c6192d7026527ea9e715026e -->|"GENERATED_FROM"| Package_d4e1cfd78cac5756637edc77891b92db
    Package_40dc8ad2d3f1c0d51d83ce2cb7275097 -->|"GENERATED_FROM"| Package_2b601c6a0e86e80fea172ec2d083c246
    Package_0d22b34f88d505664fd6421511201263 -->|"GENERATED_FROM"| Package_6fe9116dcec0977843a00c19b1c5f23b
    Package_e60638ed22baa7feec132360952543d2 -->|"GENERATED_FROM"| Package_d37f35e75540324e214bb7b269c616a7
    Package_b16b30fb23a4060fa6719111206f60ef -->|"GENERATED_FROM"| Package_d4e1cfd78cac5756637edc77891b92db
    Package_d3844c290584d158fda1b93bfad5ca6f -->|"GENERATED_FROM"| Package_94e1206f70525f46db46e865c625226a
    Package_bdc18f92cd0da6f5083d2ceea4a85cdd -->|"GENERATED_FROM"| Package_9b06a5d701a2dc4169712ed7e2066c65
    Package_2b9c01a24f96bc991c70c07b0b288e1a -->|"GENERATED_FROM"| Package_df9be288a38e8fef45ce5cbffda05d3a
    Package_e2fad71055ba2ac1079c725aa4d5b42c -->|"GENERATED_FROM"| Package_df9be288a38e8fef45ce5cbffda05d3a
    Package_4755d2e4fb2b18e8f9257e194b90a8c5 -->|"GENERATED_FROM"| Package_df9be288a38e8fef45ce5cbffda05d3a
    Package_f635b3896bb566b3bfbf852953aaa416 -->|"GENERATED_FROM"| Package_df9be288a38e8fef45ce5cbffda05d3a
    Package_17d2aaa0d2cf65672f738487ea49e282 -->|"GENERATED_FROM"| Package_6d455ad9d48fc599fb81ea78f6c4bc13
    Package_1c147f8b550f2121cff5de2da8b2166a -->|"GENERATED_FROM"| Package_7aa2e0bfbc34096e1320068ecdc27679
    Package_f61e7cd4f523785e846a81f3721fcc51 -->|"GENERATED_FROM"| Package_3288b671e27cd591730d3c825fbffe28
    Package_d1a0d2ee4302634368ffdc589b051d62 -->|"GENERATED_FROM"| Package_f58852f5537d4e85667d6dc362c1dbd0
    Package_51840d28384be8f75270e4324997a514 -->|"GENERATED_FROM"| Package_0ef8bdb0a9aba50f238b4e932dc45b89
    Package_36f5ae8417ac9a47d149d7741d9b1287 -->|"GENERATED_FROM"| Package_0ef8bdb0a9aba50f238b4e932dc45b89
    Package_c08052a2d4b6c54d99f1533b46d4bd28 -->|"GENERATED_FROM"| Package_58d568dec02f159a4dcf45662c75c5a2
    Package_79a12a2652b7e5a906c6d73064ec4ce5 -->|"GENERATED_FROM"| Package_d4e1cfd78cac5756637edc77891b92db
    Package_b07bf35e19d30d52d160ced0ba5e7297 -->|"GENERATED_FROM"| Package_b2c2173c36b275dd4701ed9889325b6d
    Package_2125d51c5fcf478bebdd94c527da6934 -->|"GENERATED_FROM"| Package_7a951f60f30b7b471fdd6b15a5b0f2b6
    Package_5bb59cc08e09d2d13581a4d6a603a8dd -->|"GENERATED_FROM"| Package_7f7e7b711aaaa224d1ab3f6e22951c64
    Package_75c969fd64c908a6587692b3aa9b58de -->|"GENERATED_FROM"| Package_aae09e1686b924f2798c9216df4f33c6
    Package_9e3acb9bd967a963b2b0956a83e4879d -->|"GENERATED_FROM"| Package_94e1206f70525f46db46e865c625226a
    Package_a4579486a3fa1e1e60da1bdfccf3d17d -->|"GENERATED_FROM"| Package_aae09e1686b924f2798c9216df4f33c6
    Package_56644af365cb2702904c1426efb165de -->|"GENERATED_FROM"| Package_d4e1cfd78cac5756637edc77891b92db
    Package_eb12cc362f1bad39d9b18796a4e64c8a -->|"GENERATED_FROM"| Package_40bceca5070cfa30065766d28046a71e
    Package_e56f5a900043acad2268b5e7258ef4fc -->|"GENERATED_FROM"| Package_98a1a0dc5f1ccffceedb4e80f6538d39
    Package_df64415e6efeffe8406d3498bcfd2efc -->|"GENERATED_FROM"| Package_4ac6b4d63150802b6b44793088a3fd51
    Package_05d3b3f48a753cd61e4b021d47a22860 -->|"GENERATED_FROM"| Package_d4e1cfd78cac5756637edc77891b92db
    Package_6f38145d0a8c5e6470fd70ec0de4d211 -->|"GENERATED_FROM"| Package_d4e1cfd78cac5756637edc77891b92db
    Package_d7e0be9a80ac513a19c68bfa4cfab6da -->|"GENERATED_FROM"| Package_94e1206f70525f46db46e865c625226a
    Package_f10dd27e0a7c860d3d51a2bab554c575 -->|"GENERATED_FROM"| Package_94e1206f70525f46db46e865c625226a
    Package_05ddc2e1815a825c594767d32c772e37 -->|"GENERATED_FROM"| Package_7a951f60f30b7b471fdd6b15a5b0f2b6
    Package_ec48f1546ec934252547fbb776fc8afd -->|"GENERATED_FROM"| Package_4ac6b4d63150802b6b44793088a3fd51
    Package_a834bc8fafa2435695e8d58c66be9039 -->|"GENERATED_FROM"| Package_894bc102a72a7decd42d26c33719ae20
    Package_f5cc69ee4bd01356845109ecbddb0588 -->|"GENERATED_FROM"| Package_7aa2e0bfbc34096e1320068ecdc27679
    Package_f5167d4f8ef0a2d3cd4bc8876f8f2e4a -->|"GENERATED_FROM"| Package_7ed7ec2eb9aa83ec81ef0457ec0b3213
    Package_cc5987b162950271528456cefbef2354 -->|"GENERATED_FROM"| Package_b93822c63ad7944986d18ad15fb6d115
    Package_cf112f620a801e8e350730dfde3c4a7b -->|"GENERATED_FROM"| Package_2ba1d3a7661da39ebdc1eab62057f403

    %% Legend
    legend["Legend:<br/>Blue = Document<br/>Purple = Package (APPLICATION)<br/>Orange = Package (SOURCE)<br/>Green = File<br/>Orange = Snippet
📄 License
⬇️ Download
🚛 Supplier
💥 Originator
⛔️ NOASSERTION / unset"]
    style legend fill:#fafafa,stroke:#666,stroke-width:1px,stroke-dasharray: 5 5
